eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_IP}:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${CLIENT_IP}
    instance-id: ${spring.application.name}:${random.value}