server:
  port: 9003
  address: 0.0.0.0

logging:
  level:
    org.springframework.security.oauth2: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          google:
            user-name-attribute: email
        registration:
          google-idp:
            client-id: ${GOOGLE_CLIENT_ID}
            client-name: oauth2-tutorial-client
            client-secret: ${GOOGLE_CLIENT_SECRET}
            provider: google
            scope: openid, profile, email
